site_name:        ZeeQL
site_url:         http://zeeql.io
site_author:      ZeeZide GmbH
copyright:        Â© ZeeZide GmbH 2019
repo_url:         https://github.com/zeeql/
  
docs_dir:    content
site_dir:    docs

theme: 
  name:       readthedocs
  custom_dir: custom_theme
extra_css:   [ extra.css ]

nav:
  - 'Introduction':    'index.md'
  - 'About':           'about.md'
  